# Generated by Django 4.1.8 on 2023-04-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="created_at",
        ),
    ]
